data:extend
{
  {
    type = "item",
    name = "electric-vehicles-lo-voltage-transformer",
    icon = "__electric-vehicles-reborn__/graphics/icons/lo-voltage-transformer.png",
    icon_size = 32,
    placed_as_equipment_result = "electric-vehicles-lo-voltage-transformer",
    flags = {"goes-to-main-inventory"},
    subgroup = "electric-vehicles-equipment",
    order = "c",
    stack_size = 10,
  },
  {
    type = "item",
    name = "electric-vehicles-hi-voltage-transformer",
    icon = "__electric-vehicles-reborn__/graphics/icons/hi-voltage-transformer.png",
    icon_size = 32,
    placed_as_equipment_result = "electric-vehicles-hi-voltage-transformer",
    flags = {"goes-to-main-inventory"},
    subgroup = "electric-vehicles-equipment",
    order = "d",
    stack_size = 10,
  },
  {
    type = "item-with-entity-data",
    name = "electric-vehicles-electric-locomotive",
    icon = "__electric-vehicles-reborn__/graphics/icons/electric-locomotive-2.png",
    icon_size = 32,
    flags = {"goes-to-quickbar"},
    subgroup = "transport",
    order = "a[train-system]-f[electric-locomotive]",
    place_result = "electric-vehicles-electric-locomotive",
    stack_size = 1,
  },
  {
    type = "item-with-entity-data",
    name = "electric-vehicles-electric-car",
    icon = "__electric-vehicles-reborn__/graphics/icons/electric-car.png",
    icon_size = 32,
    flags = {"goes-to-quickbar"},
    subgroup = "transport",
    order = "b[personal-transport]-c[car]",
    place_result = "electric-vehicles-electric-car",
    stack_size = 1
  },
  {
    type = "item-with-entity-data",
    name = "electric-vehicles-electric-tank",
    icon = "__electric-vehicles-reborn__/graphics/icons/electric-tank.png",
    icon_size = 32,
    flags = {"goes-to-quickbar"},
    subgroup = "transport",
    order = "b[personal-transport]-d[tank]",
    place_result = "electric-vehicles-electric-tank",
    stack_size = 1
  },
  {
    type = "item",
    name = "electric-vehicles-regen-brake-controller",
    icon = "__electric-vehicles-reborn__/graphics/icons/regen-brake-controller.png",
    icon_size = 32,
    placed_as_equipment_result = "electric-vehicles-regen-brake-controller",
    flags = {"goes-to-main-inventory"},
    subgroup = "electric-vehicles-equipment",
    order = "e",
    stack_size = 10,
  },
}
